# -*- coding: utf-8 -*-
"""Kasus7Adaline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jr_VSzqxarPbw-ZRB0kb1Fgb9rJd6398
"""

import numpy as np

print('\t      TUGAS KELOMPOK I JST \t')
print('\t     JARINGAN SYARAF TIRUAN \t')
print('\t KASUS 7 DENGAN JARINGAN ADALINE \t')
print('  ')
print('  ')
# input
x = [[-1,1,1,-1,1],[1,-1,1,-1,1],[1,1,-1,-1,1],[1,1,1,1,1]]
t = [[1,1,-1,-1],[-1,-1,1,1]]
w = [0,0,0,0,0,]
ww = [[0,0,0,0,0],[0,0,0,0,0]]
ep = 0
a = 4
db = 1
alpha = float(input('Masukkan nilai alpha: '))
toleransi = float(input('Masukkan nilai toleransi: '))
print('  ')

# proses iterasi
if db > toleransi :
  ep += 1
  for j in range (0,2) :
    w= [0,0,0,0,0,]
    print('untuk t = ',j+1)
    for i in range (0,4) :
      for k in range (0,5) :
      # proses pencarian net
        net = w[i]*x[i][k]
      print ('[net] untuk epoch',ep,'baris ke ',j+1,'kolom ke ',i+1,"=",net)
      err = (t[j][i]-net)
       # proses menghitung delta bobot
      if net!= t[j][i]:
        dw=np.dot(alpha*err,x[i])
        # proses menghitung bobot baru
        w += dw
        print('dw =',dw)
        print('w  =',w)
        print(' ')
        ww[j]= w
      db = max(dw)
      print(' ')
      

print('jadi bobot baru yang diperoleh adalah :')
for j in range (0,2) :
  print('w untuk t ke-',j+1,'=',ww[j])
  print(' ')

# proses pengenalan pola
print('Hasil setelah pengenalan Pola = ')
th = 0
yy = [[0,0,0,0],[0,0,0,0]]
for j in range (0,2) :
  for i in range (0,4):
    fnet = np.dot(x[i],ww[j])
    print('fnet untuk ke',j+1,i+1,'=',fnet)
    # proses aktivasi
    if fnet >= th:
      y = 1
    else :
      y = -1
  
    yy[j][i]=y
print('  ')
for j in range (0,2) :
  print('output ke-',j+1,yy[j])
if (yy == t) :
  print ('Jaringan dapat mengenali pola') 
else :
  print ('Jaringan tidak dapat mengenali pola')
print('  ')